FROM nginx:alpine

# Копируем свой nginx.conf (если нужно, иначе можно использовать дефолтный)
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Копируем статику (например, dist/ после сборки фронта) внутрь стандартной папки Nginx
# COPY ./dist /usr/share/nginx/html

# Открываем порт 80 (дефолт для Nginx)
EXPOSE 80